name: customer_support_bot
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - boto3=1.12.21
  - botocore=1.15.21
  - ca-certificates=2020.1.1
  - certifi=2019.11.28
  - cffi=1.14.0
  - chardet=3.0.4
  - click=7.1.1
  - cryptography=2.8
  - cudatoolkit=10.1.243
  - docutils=0.15.2
  - flask=1.1.1
  - freetype=2.9.1
  - idna=2.9
  - intel-openmp=2020.0
  - itsdangerous=1.1.0
  - jinja2=2.11.1
  - jmespath=0.9.5
  - joblib=0.14.1
  - jpeg=9b
  - libblas=3.8.0
  - libcblas=3.8.0
  - liblapack=3.8.0
  - libpng=1.6.37
  - libtiff=4.1.0
  - markupsafe=1.1.1
  - mkl=2020.0
  - ninja=1.9.0
  - numpy=1.18.1
  - olefile=0.46
  - openssl=1.1.1d
  - pillow=7.0.0
  - pip=20.0.2
  - pycparser=2.20
  - pyopenssl=19.1.0
  - pysocks=1.7.1
  - python=3.7.6
  - python-dateutil=2.8.1
  - python_abi=3.7
  - pytorch=1.4.0
  - regex=2020.2.20
  - requests=2.23.0
  - s3transfer=0.3.3
  - sacremoses=0.0.38
  - setuptools=46.0.0
  - six=1.14.0
  - sqlite=3.31.1
  - tk=8.6.8
  - torchvision=0.5.0
  - tqdm=4.43.0
  - transformers=2.1.1
  - urllib3=1.25.7
  - werkzeug=1.0.0
  - wheel=0.34.2
  - xz=5.2.4
  - zlib=1.2.11
  - zstd=1.3.7

